/*
TC - O(KlogK), where K is the number of pairs generated by the worker-bike cross calculations (NxM)
SC - 0(N*M), since we create a structure to hold these many distance triplets

Issues Faced - did not think of better solution (bucket sort to reduce sorting complexity). But was able to think of this entire approach myself. Need to revisit the other bucket sort problem (queue reconstruction by height) to internalize the core logic.

Solved on LeetCode - Yes

*/


class Solution {
    public:
        /**
         * @param workers: workers' location
         * @param bikes: bikes' location
         * @return: assign bikes
         */
        vector<int> assignBikes(vector<vector<int>> &workers, vector<vector<int>> &bikes) {
            int n = workers.size();
    
            int m = bikes.size();
    
            vector<pair<pair<int, int>, int>> data;
    
            for (int i = 0 ; i < n ; i ++) {
                for (int j = 0 ; j < m ; j++) {
                        int mh_dist = abs(workers[i][0] - bikes[j][0]) + abs(workers[i][1] - bikes[j][1]);
                        data.push_back(make_pair(make_pair(i, j), mh_dist));
                }
            }
    
            sort(data.begin(), data.end(), [] (const pair<pair<int, int>, int> &a, const pair<pair<int, int>, int> &b) {
                if (a.second < b.second) {
                    return true;
                } else if (a.second > b.second) {
                    return false;
                } else {
                    int aWorker = a.first.first;
                    int aBike = a.first.second;
                    int bWorker = b.first.first;
                    int bBike = b.first.second;
                    if (aWorker < bWorker) {
                        return true;
                    } else if (aWorker > bWorker) {
                        return false;
                    } else {
                        if (aBike <= bBike) {
                            return true;
                        } else {
                            return false;
                        }
                    }
                }
            });
    
            vector<bool> seenWorkers(n, false);
            vector<bool> seenBikes(m, false);
    
            vector<int> res(n, -1);
            
            for (auto x: data) {
                int currWorker = x.first.first;
                int currBike = x.first.second;
    
                if (seenWorkers[currWorker] || seenBikes[currBike]) {
                    continue;
                }
    
                seenWorkers[currWorker] = true;
                seenBikes[currBike] = true;
    
                res[currWorker] = currBike;
            }
    
            return res;
        }
    };
